[terminal]
[terminal.shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"
